global:
  imageRegistry: public.ecr.aws
  security:
    allowInsecureImages: true

redis:
  architecture: standalone

  auth:
    enabled: true
    existingSecret: redis-credentials
    # password 값은 Kubernetes Secret(redis-credentials)에서 주입

  master:
    persistence:
      enabled: false

  image:
    repository: bitnami/redis
    tag: 8.6.0

