apiVersion: v1
kind: ConfigMap
metadata:
  name: baro-order-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8083"
  SPRING_DATASOURCE_URL: "jdbc:mysql://my-mysql.db.svc.cluster.local:3306/baro_order?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useUnicode=true"
  SHOPPING_SERVICE_URL: "http://baro-shopping:8080"
