apiVersion: v1
kind: Service
metadata:
  name: baro-shopping
  labels:
    app: baro-shopping
spec:
  type: ClusterIP
  selector:
    app: baro-shopping
  ports:
    - port: 8080
      targetPort: 8082
      protocol: TCP
      name: http
