apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.8
          imagePullPolicy: IfNotPresent
          env:
            - name: INFLUXDB_DB
              value: k6
          ports:
            - containerPort: 8086
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

