apiVersion: v1
kind: Service
metadata:
  name: baro-ai
  labels:
    app: baro-ai
spec:
  type: ClusterIP
  selector:
    app: baro-ai
  ports:
    - port: 8080
      targetPort: 8092
      protocol: TCP
      name: http
