spring:
  application:
    name: baro-sample
  profiles:
    active: local

api:
  v1: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.barofarm.sample: DEBUG
