server:
  port: 8090

spring:
  # 각자 db의 url, username, pw 입력
  datasource:
    url: jdbc:mysql://localhost:3306/barodb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: baro-sample-group
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "com.barofarm.sample.*"
        spring.json.use.type.headers: false
