apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baro-prod

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: config
  component: cloud

images:
  - name: ghcr.io/do-develop-space/config
    newTag: latest

