global:
  imageRegistry: public.ecr.aws
  security:
    allowInsecureImages: true

mysql:
  auth:
    existingSecret: mysql-credentials
    database: "baro_db"
    username: "baro_user"

  architecture: standalone

  primary:
    persistence:
      enabled: true
      storageClass: gp3-ebs
      size: 4Gi

    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    service:
      type: NodePort
      nodePorts:
        mysql: 32000

  image:
    repository: bitnami/mysql

