apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: baro-prod
  labels:
    app: opa
    component: cloud
spec:
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: http
  selector:
    app: opa
