apiVersion: v1
kind: Service
metadata:
  name: baro-payment
  namespace: baro-prod
  labels:
    app: baro-payment
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: baro-payment

