image:
  registry: public.ecr.aws
  repository: bitnami/kafka
  tag: 3.7.0

kraft:
  enabled: true
  controllerQuorumVoters: "0@my-kafka-controller-0.my-kafka-controller-headless.kafka.svc.cluster.local:9093"

controller:
  replicaCount: 1  # 컨트롤러 1개

broker:
  replicaCount: 1  # 브로커 1개

listeners:
  client:
    protocol: PLAINTEXT
  interBroker:
    protocol: PLAINTEXT
  external:
    enabled: false

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabledMechanisms: []

persistence:
  enabled: true
  storageClass: gp3-ebs
  size: 2Gi

zookeeper:
  enabled: false  # KRaft에서는 Zookeeper 끔
