global:
  security:
    allowInsecureImages: true

image:
  registry: public.ecr.aws
  repository: bitnami/kafka
  tag: 3.7.0

replicaCount: 1

listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    enabled: false

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabledMechanisms: []

persistence:
  enabled: true
  storageClass: gp3-ebs
  size: 2Gi

zookeeper:
  enabled: false
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: gp3-ebs
    size: 1Gi

kraft:
  enabled: true

clusterId: ""
existingKraftSecret: ""
kraftVersion: 1

controller:
  replicaCount: 1

broker:
  replicaCount: 1
