apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baro-prod

resources:
  - namespace.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      environment: production
