apiVersion: v1
kind: ConfigMap
metadata:
  name: baro-sample-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8090"
  SPRING_DATASOURCE_URL: "jdbc:mysql://my-mysql.db.svc.cluster.local:3306/baro_db"
