apiVersion: apps/v1
kind: Deployment
metadata:
  name: baro-sample
  labels:
    app: baro-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baro-sample
  template:
    metadata:
      labels:
        app: baro-sample
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: baro-sample
          image: 299369991605.dkr.ecr.ap-northeast-2.amazonaws.com/baro-prod/baro-sample:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
              name: http
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://my-mysql.db.svc.cluster.local:3306/baro_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            - name: REDIS_HOST
              value: my-redis-master.cache.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-kafka.kafka.svc.cluster.local:9092
