apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: baro-sample
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: baro-sample
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scheme: http
